Fix/spacing in footer section
TheGymRwanda/zzz-unit8-green pull request #19
Opened 2022-12-12 14:00 UTC by Fidesnoella

# Description

Add  margin left to the footer and font size to tablet break point.

Fixes # (issue)

Fix font size to tablet version

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] npm run dev
- [ ] npm run build

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent

2022-12-18 07:36 UTC, esther921 requested changes

2022-12-18 07:36 UTC, esther921 commented on tailwind.config.js
> +      maxWidth: {
Don't you think that with changing the maxWidth you will change alot on the wrapper set I suggest you keep this and also add the maxwidth for the wrapper!

2022-12-18 07:36 UTC, esther921 commented on tailwind.config.js
> +        "6.5xl": "76.3125rem"
` maxWidth: {
        90: "90rem",
      },`

This is the standard thin and you can try to add it to and test the effect on your wrapper

2022-12-20 09:38 UTC, Stevenkwizera06 requested changes
Good work Noella try to change in the Impressum Privacy add a slash between those two words

2022-12-21 17:05 UTC, esther921 approved these changes
LGTM

2022-12-22 06:10 UTC, NNesta approved these changes
LGTM

2022-12-22 06:28 UTC, Stevenkwizera06 approved these changes

2022-12-22 06:57 UTC, merged