Fix/header section
TheGymRwanda/zzz-unit8-green pull request #20
Opened 2022-12-14 17:47 UTC by iamzilfa

# Description

Fixing the space in the header section 

Fixes # (issue)

-  Space between the logo and paragraph in all breakpoints 
- Margins  on both sides,
-  Removed arbitrary values

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] npm run build
- [ ] npm run dev

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent

2022-12-20 09:22 UTC, esther921 commented on public/assets/images/arrow_small.svg
> +<svg width="14" height="13.36" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
I suggest you create one component in which you return all the arrows that will be needed and we can be exporting them! This is an example to it!

`import React from "react";

export const ArrowPointingRight = () => {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="%23FFFFFF"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="M5 12h13M12 5l7 7-7 7" />
    </svg>
  );
};

export const ArrowPointing = () => {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="%23FFFFFF"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="M5 12h13M12 5l7 7-7 7" />
    </svg>
  );
};
`

2022-12-20 09:30 UTC, esther921 requested changes
The code

2022-12-20 09:30 UTC, esther921 commented on public/assets/images/arrow_small.svg
> +<svg width="14" height="13.36" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
I suggest you create one component in which you return all the arrows that will be needed and we can be exporting them! This is an example to it!

`import React from "react";

export const ArrowPointingRight = () => {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="%23FFFFFF"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="M5 12h13M12 5l7 7-7 7" />
    </svg>
  );
};

export const ArrowPointing = () => {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="%23FFFFFF"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="M5 12h13M12 5l7 7-7 7" />
    </svg>
  );
};
`

2022-12-20 09:30 UTC, esther921 commented on components/sections/Header.jsx
> +import ArrowSmall from "../../public/assets/images/arrow_small.svg";
I suggest you add a more descriptive name to your arrow since we are going to use the arrows from one components

2022-12-21 12:48 UTC, NNesta approved these changes
Good Job @iamzilfa

2022-12-22 16:46 UTC, esther921 approved these changes
LGTM

2022-12-22 16:46 UTC, Stevenkwizera06 approved these changes

2022-12-22 17:27 UTC, merged

2022-12-22 17:28 UTC, Fidesnoella reviewed
Well done