Ft/header section
TheGymRwanda/zzz-unit8-green pull request #8
Opened 2022-11-23 18:59 UTC by iamzilfa

# Description

Done working on the header section

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent

2022-11-24 12:58 UTC, NNesta requested changes

2022-11-24 12:58 UTC, NNesta commented on components/sections/Header.jsx
> +          Ape Unit
remove those arbitrally values on min-w-[100px] and make sure it is in rem

2022-11-25 07:22 UTC, NNesta requested changes

2022-11-25 07:22 UTC, NNesta commented on components/sections/Header.jsx
> +      <div className="grid mt-12 tablet:grid-cols-[250px_minmax(0,_1fr)] desktop:grid-cols-3">
Remove this arbitrally value of grid-cols-[250-x_minmax(0,1fr)]

2022-11-28 08:57 UTC, NNesta approved these changes
Well done

2022-11-28 09:05 UTC, esther921 approved these changes
LGTM

2022-11-28 09:07 UTC, merged